### ISSUE TITLE
::first-letter selector

### ISSUE THREAD

**Issue by arnavnagpurkar** [duocoderz/Sports-and-Fitness-Portal#4]
Instead of ```<h2><span>A</span>bout Us</h2>``` this syntax, we can use css and directly give the style to the first letter, no need to use span.
For example:
```css
h2::first-letter {
     /* Styles */
}
```
@AryanSarode18 Are you doing this or should I make the required changes?

**Comment by AryanSarode18** [comment]
There are other h2 too, which don't need the styles.
So existing code is better ig.

**Comment by arnavnagpurkar** [comment]
> There are other h2 too, which don't need the styles. So existing code is better ig.

We can add classes?
Using spans always is not a good idea.

**Comment by AryanSarode18** [comment]
classes to what?
only the first letter needs the color so how can we just give class to first letter only

**Comment by arnavnagpurkar** [comment]
> classes to what? only the first letter needs the color so how can we just give class to first letter only

The div's or headings where first letter needs styling we can add class ```first-letter``` and then style it through :
```css
.first-letter::first-letter{
     /* Styles */
}
```
